# MYSQL deployment yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: wordpress
  namespace: cep-project1
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: db
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cep-secrets
                  key: mysql-root-pwd
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: cep-secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cep-secrets
                  key: mysql-pwd
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: cep-config
                  key: DB_NAME
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-store
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-store
          persistentVolumeClaim:
            claimName: mysql-pv-claim