apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: wordpress
  namespace: cep-project1
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: db
  clusterIP: None